### ISSUE TITLE
Sample events payload is incorrect

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/webhooks-docs#11]
Since the release of 2019.4 the structure of the webhook payload has changed and should be updated to:

{ created_at: '2019-11-14T14:31:21Z',
  site_luid: 'abc',
  resource_luid: 'abc',
  event_type: 'WorkbookRefreshStarted',
  resource: 'EXTRACTS',
  resource_name: 'Workbook',
  querystring: {} }

**Comment by RussTheAerialist** [comment]
Where is the querystring parameter coming from? That's not in the payload that we are sending.

**Comment by bcantoni** [comment]
Closing due to age. If this is still a valid issue, go ahead and reopen with comments.
