### ISSUE TITLE
204 No Content does not register as a successful receipt

### ISSUE THREAD

**Issue by cfeenstra67** [tableau/webhooks-docs#12]
In the readme it says:

>When a server that has been sent a webhook request does not reply with a HTTP success code, the webhook will retry the request three times with diminishing frequency

I tried setting up my web hooks returning a `204 No Content` response, but I saw in the logs that the web hooks were being retried 3 times w/ diminishing frequency. After changing the status code to 200 retries to not occur. Not an issue for me anymore, just opening this to flag the discrepancy in case a documentation update makes sense.

EDIT: happy to provide more info to confirm this is an issue if desired

**Comment by jacalata** [comment]
All 2xx codes should be read as success, so I think a fix makes more sense than a doc update here.
