### ISSUE TITLE
Extract refresh notification

### ISSUE THREAD

**Issue by arunyadav19** [tableau/webhooks-docs#15]
Hi Team,

Is there any way to include more details in the notification sent by tableau to user about the extract refresh ?
I want to notify users on slack channel or direct message with a notification having details about extract refresh failure.
Can it be done without using any 3rd party services like Zapier / IFTTT ?

Regards,
Arun

**Comment by KarthikINV** [comment]
Hi Team, 

I too have the same requirement, any suggestion will be helpful.

**Comment by kyleroessler** [comment]
Same - the third party apps introduce a security concern that unfortunately creates quite a headache, would be great to have direct compatibility to slack.

**Comment by jacalata** [comment]
same as #20 and #22 , feature has been released.
