### ISSUE TITLE
WebhookTestResult Status:408

### ISSUE THREAD

**Issue by jerroldweewee** [tableau/webhooks-docs#17]
Hi Team,

I've created an endpoint that accepts json payload. This endpoint has been tested and verified by postman with the configurations of :

Header
- Content-Type : application/json
- Accept : application/json

Body(raw)
{
   "payload" : "payload"
}

Setting up of the webhook is successful. However, when attempted to Test the webhook, it gives the following response of unable to connect to the url "https://xxxx" with status 408.

What exactly is status 408 and why is tableau reporting an incorrect url when tests with postman works?

Thank you!!

**Comment by Voronov-Maxim-Alexandrovich** [comment]
I've got the same problem. Tableau server works fine with external webhook services, such as https://webhook.site but for our service, it gives 408 error.

Webhook logs from server:

webhooks: INFO  com.tableau.extensibility.webhooks.responder.http.HttpPostHookUtil - Sending message to https://some-internal-service/: 
webhooks: INFO  com.tableau.extensibility.webhooks.responder.http.HttpPostHookSender - IOException on posting

**Comment by exgospodin** [comment]
Im issuing same problem.
How can we fix that?

**Comment by jacalata** [comment]
Delayed response, but in July 2020 (for Tableau Online, shipped as 2020.3) we set a read timeout value which fixed the instance of 408 responses that we had found internally. Hopefully it fixed everyone else as well!

**Comment by kedohert** [comment]
When you say you set a Read TimeOut value was that on the Tableau end or the service you were sending to? I am getting this same exact error trying to send a WebHook internall to NiFi.

**Comment by jacalata** [comment]
It should indicate that the destination service is rejecting your webhook for some reason. Other causes to look at are certificates, especially self-signed certs. If you copy the webhooks outgoing POST to NiFi using curl, that should let you see the specific error being returned.

**Comment by prabhu0376** [comment]
@jacalata I also infact have been facing the same issue with web-hooks endpoint being on Power Automate generated Azure endpoints. The on prem server version is 2020.3.
Would you have any idea if the issue of Read TimeOut value was that on the Tableau end or the service you were sending to?
The certificates aren't self-signed either.

**Comment by jacalata** [comment]
You would update the timeout on the service you are sending to. Are you able to check the request directly using curl? The 408 error can be caused by a few things, because some servers will return that when various credential checks fail (e.g the self-signed certificate mentioned above).
