### ISSUE TITLE
Direct support for Slack (JSON payload error, status code 400)

### ISSUE THREAD

**Issue by kyleroessler** [tableau/webhooks-docs#20]
Likely not an error really but getting a 400 error, invalid_payload. The JSON payload being sent is not readable by my target hook (slack, in this case).  Works fine with a testing site but appears the JSON formatting could use an update to be more compatible? Cannot use third party apps like Zapier. Any updates or ideas on how I can workaround this?

**Comment by shinchris** [comment]
Hi @kyleroessler, the payload that Tableau sends is not directly compatible with what Slack expects to receive. You will need a middleman to parse out the Tableau payload and build a Slack payload. We have a tutorial on how to get this set up, [here](https://github.com/tableau/datadev-hackathon/wiki/Send-a-Slack-notification-when-a-workbook-is-updated). Hope this helps!

**Comment by kyleroessler** [comment]
Thanks @shinchris ! This is definitely helpful

**Comment by bcantoni** [comment]
@kyleroessler this is on the backlog but no estimate on whether or when it might happen. Until then, the intermediary is the recommended solution.

**Comment by willjdsouza** [comment]
really wish this could be a thing, such a pain otherwise!

**Comment by sina-z** [comment]
I have the same problem. But answers here do not make sense. When using our Tableau Dev (the instance we get when we sign up for the tableau dev program) I CAN get the message to show up in my Slack channel. But when I create a new webhook on our Tableau Server then it gives 400 error, which is the invalid payload. If Slack cannot read the response it shouldn't be able to read it in either case. Why this happens on Tableau Server and not on Tableau Online?

**Comment by illonage** [comment]
Hi everyone! Great news, we announced it [here](https://www.tableau.com/about/blog/2020/12/december-developer-platform-news-personal-access-tokens-update-auto-disabling): In the upcoming 2021.1 release, you’ll be able to create new Webhooks to Slack with no need for middleware!

@sina-z are you using your Developer Sandbox Site for testing on Tableau Online? If yes, the Developer Sandbox site is set with the last pre-release of Tableau (2021.1), allowing to test new features.

**Comment by sina-z** [comment]
Hey Gig, yes, I was testing with the Developer Sandbox Site. That's great news. I think I still owe you some details on why I found it a little bit frustrating to follow the Webhook Dev documentation. Thanks for the update btw.

**Comment by illonage** [comment]
@sina-z yes indeed, you can ping me on Slack or Twitter 😄 

For anyone interested in testing the new Payload, you can join the Tableau Developer Program and request your free developer sandbox site: https://www.tableau.com/developer

**Comment by sina-z** [comment]
@illonage any idea when it's going to be released?

**Comment by jacalata** [comment]
Tableau 2021.1 was released on March 25 and Tableau Online now works sending webhooks directly to Slack  https://www.tableau.com/support/releases/server/2021.1
