### ISSUE TITLE
Content URL in Datasource updated payload

### ISSUE THREAD

**Issue by guna24x7** [tableau/webhooks-docs#22]
The [signIn ](https://help.tableau.com/v2019.1/api/rest_api/en-us/REST/rest_api_ref.htm#sign_in)request for REST API expects content URL to set, to get the access token, this is not available part of webhook payload. 

We need to perform set of operations using REST API, upon datasource updated to get more information about the activity.

**Comment by shinchris** [comment]
For now, you can use the [query site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_sites.htm#query_site) request to get the contentUrl of a site based on the luid that's part of the webhook payload.

**Comment by jacalata** [comment]
Same request as #20 , was fixed in March 2020
