### ISSUE TITLE
Getting 4 response after creating Create_workbook webhook in Tableau

### ISSUE THREAD

**Issue by avijit3660** [tableau/webhooks-docs#23]
Hi All, 

I have created a webhook to alert on the "webhook-source-event-workbook-created" event on my Tableau Online site. However when we publish a workbook in the site it sends 4 responses. 
Is it by design or I am missing something. I have even verified that I have a single webhook in the site

Let me know please if this is by design or I am missing something. As always thanks to the community for guiding and helping us. Any other details if needed please let me know. 

Regards
Avijit

**Comment by shinchris** [comment]
Webhooks will retry up to 3 times, after the initial attempt, if the destination URL returns a non-200 response back to us. Since it's sending 4 responses, there is a good chance that the 1 webhook may be retrying to its maximum number of attempts.

**Comment by jacalata** [comment]
Closing, hopefully chris' answer sorted this out.
