### ISSUE TITLE
Typo on landing page of docs.

### ISSUE THREAD

**Issue by andre347** [tableau/webhooks-docs#31]
Than needs to be 'that' (https://help.tableau.com/current/developer/webhooks/en-us/)

![Screenshot 2021-03-17 at 12 03 44](https://user-images.githubusercontent.com/22317522/111457766-e5d77680-8718-11eb-90fc-84b1b7ed4fe3.png)

**Comment by jacalata** [comment]
not sure when it happened, but looks fixed :)
