### ISSUE TITLE
500 Error When Trying to Create Webhook

### ISSUE THREAD

**Issue by Mrkbingham** [tableau/webhooks-docs#6]
I'm receiving a 500 error when trying to create a webhook for my Tableau Online instance.  I've just used the standard Postman template and have updated the variables needed with no other modification.  500 leads me to believe it's a server issue:
{
    "error": {
        "summary": "Internal Server Error",
        "detail": "The server encountered an error and cannot complete your request. Contact your server administrator.",
        "code": "500000"
    }
}

**Comment by RussTheAerialist** [comment]
Webhooks has not been released yet, therefore you won't be able to create them until we have released them.
