### ISSUE TITLE
Not working with Tableau server 2018.2

### ISSUE THREAD

**Issue by bheem123** [tableau/webhooks-docs#7]
Does this work with Tableau Online only? I tried to use webhooks to get notified when my extract fails on Tableau Server and I received the following error in postman from my Tableau Server.

Response:

{
    "error": {
        "summary": "Resource Not Found",
        "detail": "Unknown resource '/exp/sites/ff66e08b-e7b4-4759-b21f-1fdc0e0885f9/webhooks/<Replace_Me>/test' specified in URI.",
        "code": "404003"
    }
}

Here is my webhook.

{
   "webhook": {
      "webhook-source": {
         "webhook-source-event-workbook-created": {}
      },
      "webhook-destination": {
         "webhook-destination-http": {
            "method": "POST",
            "url": "https://{my server name}/api/exp/sites/ff66e08b-e7b4-4759-b21f-1fdc0e0885f9/webhooks"
         }
      },
      "name": "webhook_refresh_fva"
   }
}

**Comment by KeshiaRose** [comment]
Webhooks hasn't been released yet so you will not be able to use them until they have been released.
